---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: Dockerfile
    repo: quay.io/ukhomeofficedigital/redis-alpine
    registry: quay.io
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BUILD_NUMBER}
      - latest
    when:
      branch:
        exclude:
        - master
      event:
      - push

- name: trivy_scan
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/trivyscanner:b82
  commands:
  - trivy --ignore-unfixed --exit-code 1 --no-progress quay.io/ukhomeofficedigital/redis-alpine:${DRONE_COMMIT_SHA}
  when:
    branch:
      exclude:
      - master
    event:
    - push
